using System;
using System.Collections.Generic;
using System.Text;

namespace PianoChordGenerator.Domain.Enums
{
    public enum ChordsEnum
    {
        None = 0,
        C_Major_Root = 1,
        C_Major_1st = 2,
        C_Major_2nd = 3,
        C_Sharp_Major_Root = 4,
        C_Sharp_Major_1st = 5,
        C_Sharp_Major_2nd = 6,
        D_Flat_Major_Root = 7,
        D_Flat_Major_1st = 8,
        D_Flat_Major_2nd = 9,
        D_Major_Root = 10,
        D_Major_1st = 11,
        D_Major_2nd = 12,
        D_Sharp_Major_Root = 13,
        D_Sharp_Major_1st = 14,
        D_Sharp_Major_2nd = 15,
        E_Flat_Major_Root = 16,
        E_Flat_Major_1st = 17,
        E_Flat_Major_2nd = 18,
        E_Major_Root = 19,
        E_Major_1st = 20,
        E_Major_2nd = 21,
        F_Major_Root = 22,
        F_Major_1st = 23,
        F_Major_2nd = 24,
        F_Sharp_Major_Root = 25,
        F_Sharp_Major_1st = 26,
        F_Sharp_Major_2nd = 27,
        G_Flat_Major_Root = 28,
        G_Flat_Major_1st = 29,
        G_Flat_Major_2nd = 30,
        G_Major_Root = 31,
        G_Major_1st = 32,
        G_Major_2nd = 33,
        G_Sharp_Major_Root = 34,
        G_Sharp_Major_1st = 35,
        G_Sharp_Major_2nd = 36,
        A_Flat_Major_Root = 37,
        A_Flat_Major_1st = 38,
        A_Flat_Major_2nd = 39,
        A_Major_Root = 40,
        A_Major_1st = 41,
        A_Major_2nd = 42,
        A_Sharp_Major_Root = 43,
        A_Sharp_Major_1st = 44,
        A_Sharp_Major_2nd = 45,
        B_Flat_Major_Root = 46,
        B_Flat_Major_1st = 47,
        B_Flat_Major_2nd = 48,
        B_Major_Root = 49,
        B_Major_1st = 50,
        B_Major_2nd = 51,
        C_Minor_Root = 52,
        C_Minor_1st = 53,
        C_Minor_2nd = 54
    }
}
